name: Deploy to EC2
on: 
  push:
    branches:
      - master
    paths:
      - 'todo/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 저장소 클론
      - name: Checkout Repository
        uses: actions/checkout@v3

      # EC2 서버에 SSH 접속 후 모든 작업 수행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. 작업 디렉토리 이동 및 최신 코드 가져오기
            mkdir -p /home/ubuntu/app/todo
            cd /home/ubuntu/app/todo
            git pull origin master

            # 2. Java 17이 설치되어 있는지 확인 (필요시 설치)
            if ! java -version 2>&1 | grep -q "17"; then
              sudo apt update
              sudo apt install openjdk-17-jdk -y
            fi

            # 3. Secrets 파일 생성
            echo -e "${{ secrets.APP_SECRET_PROPERTIES }}" > src/main/resources/application-secret.properties

            # 4. Gradle 빌드 (테스트 제외)
            chmod +x ./gradlew
            ./gradlew clean build -x test
            
            # 5. 기존 애플리케이션 종료
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            sudo docker rmi my-app || true

            # 6. JAR 파일 이동 후 Docker 빌드 및 실행
            # cp build/libs/todo-0.0.1-SNAPSHOT.jar app.jar
            sudo docker build -t my-app .
            sudo docker run -d --name my-app -p 8080:8080 my-app
