name: Deploy to EC2 using Docker
on: 
 push:
  branches:
   - master
  paths:
   - 'todo/**'
jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   # 저장소 클론
   - name: Checkout Repository
     uses: actions/checkout@v3
   # Java 17 설정
   - name: Set up JDK 17
     uses: actions/setup-java@v3
     with:
      distribution: 'temurin'
      java-version: '17'
   # Secrets 복사
   - name: Copy application-secret.properties
     run: |
      cd todo
      echo -e "${{ secrets.APP_SECRET_PROPERTIES }}" > src/main/resources/application-secret.properties
   # Gradle build 실행
   - name: Build with Gradle
     run: |
      cd todo
      chmod +x ./gradlew
      ./gradlew clean build -x test
   # 빌드된 jar파일 확인   
   - name: Check Jar file
     run: |
      ls -lh todo/build/libs/
   # EC2 서버에 SSH로 접속하여 배포
   - name: Deploy to EC2
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_SSH_KEY }}
      script: |
       mkdir -p ~/.ssh
       ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
       cd /home/ubuntu/app
       # todo 프로젝트 디렉토리로 이동
       cd todo
       scp build/libs/todo-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/todo.jar
       nohup java -jar /home/ubuntu/app/todo.jar > /home/ubuntu/app/app.log 2>&1 &
