name: Deploy to EC2 using Docker
on: 
 push:
  branches:
   - master
  paths:
   - 'todo/**'
jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   # 저장소 클론
   - name: Checkout Repository
     uses: actions/checkout@v3
   # Java 17 설정
   - name: Set up JDK 17
     uses: actions/setup-java@v3
     with:
      distribution: 'temurin'
      java-version: '17'
   # Secrets 복사
   - name: Copy application-secret.properties
     run: |
      cd todo
      echo -e "${{ secrets.APP_SECRET_PROPERTIES }}" > src/main/resources/application-secret.properties
   # Gradle build 실행
   - name: Build with Gradle
     run: |
      cd todo
      chmod +x ./gradlew
      ./gradlew clean build -x test
   # 빌드된 jar파일 확인   
   - name: Check Jar file
     run: |
      ls -lh todo/build/libs/
   # ssh key 파일 생성
   - name: Create SSH Key
     run: |
      echo "${{ secrets.EC2_SSH_KEY }}" > ~/private-key.pem
      chmod 600 ~/private-key.pem
   - name: Create SSH directory
     run: |
      mkdir -p ~/.ssh
   - name: Add known host
     run: |
      ssh-keysan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
   - name: Copy files to remote server
     run: |
      cd /home/ubuntu/app/todo
      scp build/libs/todo-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/todo.jar
      nohup java -jar /home/ubuntu/app/todo.jar > /home/ubuntu/app/app.log 2>&1 &
